<?php
$content = "";

$content = $content . "<div data-dojo-type=\"dijit/layout/BorderContainer\" style=\"width:100%,height:100%\" data-dojo-props=\"design:'sidebar', gutters:true\">\n";
$content = $content . "  <div data-dojo-type=\"dijit/layout/ContentPane\" data-dojo-props=\"region:'left'\" style=\"width:250px\">\n";
$content = $content . "    <div data-dojo-type=\"dijit/TitlePane\" data-dojo-props=\"title: 'Calendars', style:'margin-top:10px;width:250px'\">\n";
$content = $content . "      <div>\n";
$content = $content . "        <input type=\"checkbox\" id=\"maniacsEventsCalendarCheck\" data-dojo-type=\"dijit/form/CheckBox\" checked=\"true\">\n";
$content = $content . "        <label for=\"maniacsEventsCalendarCheck\">Events</label>\n";
$content = $content . "      </div>\n";
$content = $content . "      <div>\n";
$content = $content . "        <input type=\"checkbox\" id=\"maniacsGamesCalendarCheck\" data-dojo-type=\"dijit/form/CheckBox\" checked=\"true\">\n";
$content = $content . "        <label for=\"maniacsGamesCalendarCheck\">Games</label>\n";
$content = $content . "      </div>\n";
$content = $content . "      <div>\n";
$content = $content . "        <input type=\"checkbox\" id=\"maniacsPracticesCalendarCheck\" data-dojo-type=\"dijit/form/CheckBox\" checked=\"true\">\n";
$content = $content . "        <label for=\"maniacsPracticesCalendarCheck\">Practices</label>\n";
$content = $content . "      </div>\n";
$content = $content . "      <div>\n";
$content = $content . "        <input type=\"checkbox\" id=\"maniacsBirthdayasCalendarCheck\" data-dojo-type=\"dijit/form/CheckBox\" checked=\"true\">\n";
$content = $content . "        <label for=\"maniacsBirthdaysCalendarCheck\">Birthdays</label>\n";
$content = $content . "      </div>\n";
$content = $content . "    </div>\n";
$content = $content . "  </div>\n";
$content = $content . "  <div data-dojo-type=\"dijit/layout/ContentPane\" data-dojo-props=\"splitter:false, region:'center'\">\n";
$content = $content . "    <center><div id=\"eventsCalendar\"></div></center>\n";
$content = $content . "  </div>\n";
$content = $content . "  <div data-dojo-type=\"dijit/layout/ContentPane\" data-dojo-props=\"splitter:false, region:'right'\" style=\"width:250px\">\n";
$content = $content . "    <div data-dojo-type=\"dijit/TitlePane\" data-dojo-props=\"title: 'Events', style:'margin-top:10px;width:250px'\">\n";
$content = $content . "      <center>Event Information:</center>\n";
$content = $content . "		<div><span>Summary:</span></div>\n";
$content = $content . "		<div id=\"maniacsCalendarEventDesc\" data-dojo-type=\"dijit/form/TextBox\" style=\"width:225px;\" data-dojo-props=\"disabled:true\"></div>\n";
$content = $content . "		<div style=\"margin-top:10px\"><span>Start:</span></div>\n";
$content = $content . "		<div>\n";
$content = $content . "			<div id=\"maniacsCalendarStartDate\" data-dojo-type=\"dijit/form/DateTextBox\" style=\"width:120px;\" data-dojo-props=\"disabled:true\"></div>\n";
$content = $content . "			<div id=\"maniacsCalendarStartTime\" data-dojo-type=\"dijit/form/TimeTextBox\" style=\"width:100px;\" data-dojo-props=\"disabled:true\"></div>\n";
$content = $content . "		</div>\n";
$content = $content . "		<div style=\"margin-top:10px\"><span>End:</span></div>\n";
$content = $content . "           <div>\n";
$content = $content . "			<div id=\"maniacsCalendarEndDate\" data-dojo-type=\"dijit/form/DateTextBox\" style=\"width:120px;\" data-dojo-props=\"disabled:true\" ></div>\n";
$content = $content . "			<div id=\"maniacsCalendarEndTime\" data-dojo-type=\"dijit/form/TimeTextBox\" style=\"width:100px;\" data-dojo-props=\"disabled:true\" ></div>\n";
$content = $content . "		  </div>\n";
$content = $content . "		<div style=\"margin-top:10px\"><span>Calendar:</span></div>\n";
$content = $content . "		<select id=\"maniacsCalendarType\" data-dojo-type=\"dijit/form/ComboBox\" style=\"width:225px;\" data-dojo-props=\"disabled:true\" >\n";
$content = $content . "			<option>Events</option>\n";
$content = $content . "			<option>Games</option>\n";
$content = $content . "			<option>Practices</option>\n";
$content = $content . "			<option>Birthdays</option>\n";
$content = $content . "		</select>\n";
$content = $content . "      <div>\n";
$content = $content . "        <input type=\"checkbox\" id=\"maniacsAllDayEvent\" data-dojo-type=\"dijit/form/CheckBox\">\n";
$content = $content . "        <label for=\"maniacsAllDayEvent\">All-Day</label>\n";
$content = $content . "      </div>\n";
$content = $content . "    </div>\n";
$content = $content . "  </div>\n";
$content = $content . "</div>\n";
echo $content;
?>

