<?php
  include "class/ManiacsClass.php";
  $maniacs = new ManiacsClass();
  $return = $maniacs->csvToArrayV1("/var/www/html/maniacs/gc-maniacs.csv", ",", 
                                   array("player_id","games_played","plate_appearances", "at_bats", "hits", "single", 
                                         "dbl", "triple", "homerun", "rbi", "runs","hbp", "roe", "fielders_choice",
                                         "catcher_int", "walks", "strikeouts", "avg", "obp", "slugging", "ops",
                                         "pa_per_bb","bb_per_k", "c_percent", "stolenbase", "caughtstealing",
                                         "stolenbase_percent", "pik", "gidp", "gitp", "extrabasehits", "totalbases", "ab_per_hr",
                                         "ba_risp", "ps", "ps_per_pa", "two_s_plus_three","two_s_plus_t_percent",
                                         "six_plus", "six_plus_percent", "sac", "sf", "lob", "two_out_rbi", "hhb",
                                         "qab", "qab_percent", "pitching_innings_pitched","pitching_games_pitched",
                                         "pitching_games_started", "pitching_wins", "pitching_losses", "pitching_saves",
                                         "pitching_save_opp", "pitching_blown_saves","pitching_save_percent", 
                                         "pitching_hits_allowed", "pitching_runs_allowed", "pitching_earned_runs",
                                         "pitching_walks", "pitching_strikeouts", "pitching_hit_batters", "pitching_era",
                                         "pitching_whip", "pitching_batters_faced", "pitching_total_pitches",
                                         "pitching_total_strikes", "pitching_total_balls", "pitching_pitches_per_inning",
                                         "pitching_pitches_per_batters_faced", "pitching_less_than_three",
                                         "pitching_less_than_three_percent", "pitching_leadoff_out",
                                         "pitching_innings_first2out", "pitching_123inn", "pitching_less_than_13pitches",
                                         "pitching_fielding_independent_pitching", "pitching_strike_percent",
                                         "pitching_first_pitch_strikes", "pitching_first_pitch_strikes_percent",
                                         "pitching_first_pitch_strike_out_percent", "pitching_first_pitch_strike_walks",
                                         "pitching_first_pitch_strikes_hits", "pitching_walks_per_inning","pitching_zero_walk_innings",
                                         "pitching_walks_that_score", "pitching_leadoff_walk","pitching_leadoff_walk_scored", 
                                         "pitching_wild_pitches","pitching_atbats_against", "pitching_swing_miss", "pitching_swing_miss_percent",
                                         "pitching_strikeouts_per_regulation_game", "pitching_strikeouts_per_batter_faced",
                                         "pitching_strikeouts_per_walk", "pitching_weak_percent", "pitching_hardhit_ball_percent",
                                         "pitching_groundball_percent", "pitching_flyball_percent", "pitching_groundouts",
                                         "pitching_flyouts", "pitching_go_fo_ratio", "pitching_opponent_batting_avg",
                                         "pitching_homeruns_allowed", "pitching_left_on_base", "pitching_balks",
                                         "pitching_picked_off", "pitching_stolenbases_allowed", "pitching_caught_stealing",
                                         "pitching_stolenbase_percent", "pitching_num_fastballs","pitching_num_fastballs_strikes",
                                         "pitching_fastballs_strikes_percent","pitching_num_curveballs","pitching_num_curveballs_strikes",
                                         "pitching_curveballs_strikes_percent","pitching_num_changeups","pitching_num_changeups_strikes",
                                         "pitching_changeups_strikes_percent","pitching_num_riseballs","pitching_num_riseballs_strikes",
                                         "pitching_riseballs_strikes_percent","pitching_num_dropballs","pitching_num_dropballs_strikes",
                                         "pitching_dropballs_strikes_percent","pitching_num_screwballs","pitching_num_screwballs_strikes",
                                         "pitching_screwballs_strikes_percent","pitching_num_offspeed","pitching_num_offspeed_strikes",
                                         "pitching_offspeed_strikes_percent","fielding_total_chances","fielding_assists",
                                         "fielding_putouts", "fielding_errors", "fielding_double_plays", "fielding_triple_plays",
                                         "fielding_field_percent", "catching_innings_caught", "catching_passed_balls",
                                         "catching_stolen_bases_allowed", "catching_caught_stealing", "catching_caught_stealing_percent",
                                         "catching_picked_off", "catching_catcher_interference"), 
                                   -1);
//  print_r($return[1]);
  $maniacs->ImportRosterStats($return);
?>

